(define-module (ripgrep)
  #:use-module (gnu packages crates-io)
  #:use-module (guix build-system cargo)
  #:use-module (guix download)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages))

(define-public ripgrep
  (package
    (name "ripgrep")
    (version "11.0.1")
    (source
     (origin
       (method url-fetch)
       (uri (crate-uri "ripgrep" version))
       (file-name
        (string-append name "-" version ".tar.gz"))
       (sha256
        (base32
         "0bn40lz9n08llq615p4qqqbi24zbkf0appfx3zgxg34a86ga9zds"))))
    (build-system cargo-build-system)
    (arguments
     `(#:cargo-inputs
       (("rust-aho-corasick" ,rust-aho-corasick-0.7)
        ("rust-atty" ,rust-atty-0.2)
        ("rust-bitflags-1" ,rust-bitflags-1)
        ("rust-bstr" ,rust-bstr-0.1)
        ("rust-bytecount" ,rust-bytecount-0.5)
        ("rust-byteorder" ,rust-byteorder-1.3)
        ("rust-cc" ,rust-cc-1.0)
        ("rust-cfg-if" ,rust-cfg-if-0.1)
        ("rust-clap" ,rust-clap-2)
        ("rust-crossbeam-channel" ,rust-crossbeam-channel-0.3)
        ("rust-crossbeam-utils" ,rust-crossbeam-utils-0.6)
        ("rust-encoding-rs" ,rust-encoding-rs-0.8)
        ("rust-encoding-rs-io" ,rust-encoding-rs-io-0.1)
        ("rust-fnv" ,rust-fnv-1.0)
        ("rust-globset" ,rust-globset-0.4)
        ("rust-grep" ,rust-grep-0.2)
        ("rust-grep-cli" ,rust-grep-cli-0.1)
        ("rust-grep-matcher" ,rust-grep-matcher-0.1)
        ("rust-grep-pcre2" ,rust-grep-pcre2-0.1)
        ("rust-grep-printer" ,rust-grep-printer-0.1)
        ("rust-grep-regex" ,rust-grep-regex-0.1)
        ("rust-grep-searcher" ,rust-grep-searcher-0.1)
        ("rust-ignore" ,rust-ignore-0.4)
        ("rust-itoa" ,rust-itoa-0.4)
        ("rust-lazy-static" ,rust-lazy-static-1.3)
        ("rust-libc" ,rust-libc-0.2)
        ("rust-log" ,rust-log-0.4)
        ("rust-memchr" ,rust-memchr-2.2)
        ("rust-memmap" ,rust-memmap-0.7)
        ("rust-num-cpus" ,rust-num-cpus-1.10)
        ("rust-packed-simd" ,rust-packed-simd-0.3)
        ("rust-pcre2" ,rust-pcre2-0.2)
        ("rust-pcre2-sys" ,rust-pcre2-sys-0.2)
        ("rust-pkg-config" ,rust-pkg-config-0.3)
        ("rust-proc-macro2" ,rust-proc-macro2-1.0)
        ("rust-quote" ,rust-quote-1.0)
        ("rust-regex" ,rust-regex-1.1)
        ("rust-regex-automata" ,rust-regex-automata-0.1)
        ("rust-regex-syntax" ,rust-regex-syntax-0.6)
        ("rust-ryu" ,rust-ryu-1.0)
        ("rust-same-file" ,rust-same-file-1.0)
        ("rust-serde-json" ,rust-serde-json-1.0)
        ("rust-smallvec" ,rust-smallvec-0.6)
        ("rust-strsim" ,rust-strsim-0.8)
        ("rust-syn" ,rust-syn-1.0)
        ("rust-termcolor" ,rust-termcolor-1.0)
        ("rust-textwrap" ,rust-textwrap-0.11)
        ("rust-thread-local" ,rust-thread-local-0.3)
        ("rust-unicode-width" ,rust-unicode-width-0.1)
        ("rust-unicode-xid" ,rust-unicode-xid-0.2)
        ("rust-ucd-util" ,rust-ucd-util-0.1)
        ("rust-utf8-ranges" ,rust-utf8-ranges-1.0)
        ("rust-walkdir" ,rust-walkdir-2.2)
        ("rust-winapi" ,rust-winapi-0.3)
        ("rust-winapi-util" ,rust-winapi-util-0.1)
        ("rust-wincolor" ,rust-wincolor-1.0)
        ("rust-quote" ,rust-quote-0.6))
       #:cargo-development-inputs
       (("rust-clap" ,rust-clap-2)
        ("rust-lazy-static" ,rust-lazy-static-1.3)
        ("rust-serde" ,rust-serde-1.0)
        ("rust-serde-derive" ,rust-serde-derive-1.0))))
    (home-page
     "https://github.com/BurntSushi/ripgrep")
    (synopsis
     "Line-oriented search tool")
    (description
     "ripgrep is a line-oriented search tool that recursively searches
your current directory for a regex pattern while respecting your
gitignore rules.  ripgrep has first class support on Windows, macOS
and Linux")
    (license `(,license:unlicense ,license:expat))))
